# Generated by Django 3.1.1 on 2020-09-24 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags', '0001_initial'),
        ('postings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='posting',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='posting',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='posting',
            name='hashtags',
            field=models.ManyToManyField(related_name='postings', to='hashtags.DefaultTag'),
        ),
        migrations.AddField(
            model_name='posting',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Postings', to='postings.postingtype'),
        ),
    ]
