# Generated by Django 3.1.1 on 2020-09-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags', '0001_initial'),
        ('postings', '0002_auto_20200924_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='postings', to='hashtags.DefaultTag'),
        ),
    ]
