# Generated by Django 3.1.1 on 2020-10-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0003_auto_20200924_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
