# Generated by Django 3.1.1 on 2020-10-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0005_auto_20201013_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('deadline', models.DateTimeField(null=True)),
                ('host', models.CharField(max_length=100, null=True)),
                ('host_info', models.CharField(max_length=100, null=True)),
                ('award', models.CharField(max_length=100, null=True)),
                ('detail', models.TextField()),
            ],
        ),
    ]
