# Generated by Django 3.1.1 on 2020-10-15 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags', '0002_defaulttag_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaulttag',
            name='time',
        ),
    ]
