# Generated by Django 3.1.1 on 2020-10-14 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hashtags', '0001_initial'),
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('postings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bookmarked_posts',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_by', to='postings.Posting'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to='postings.postingtype'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='users', to='hashtags.DefaultTag'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='interests',
            field=models.ManyToManyField(blank=True, to='accounts.Interest'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='written_posts',
            field=models.ManyToManyField(blank=True, to='postings.Posting'),
        ),
    ]
