# Generated by Django 3.1.1 on 2020-09-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200924_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='interests',
            field=models.ManyToManyField(blank=True, to='accounts.Interest'),
        ),
    ]
