# Generated by Django 3.1.1 on 2020-09-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0002_auto_20200924_1812'),
        ('accounts', '0009_auto_20200924_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bookmarked_posts',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_by', to='postings.Posting'),
        ),
    ]
