# Generated by Django 3.1.1 on 2020-09-24 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200924_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bookmarked_posts',
        ),
    ]
