# Generated by Django 3.1.1 on 2020-10-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0004_posting_image'),
        ('accounts', '0012_auto_20201013_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bookmarked_posts',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_by', to='postings.Posting'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='written_posts',
            field=models.ManyToManyField(to='postings.Posting'),
        ),
    ]
