# Generated by Django 3.1.1 on 2020-10-13 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0005_auto_20201013_1034'),
        ('hashtags', '0001_initial'),
        ('accounts', '0014_auto_20201013_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to='postings.postingtype'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='users', to='hashtags.DefaultTag'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='want_to_say',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('detail', models.TextField(null=True)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experience', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
